### ISSUE TITLE
Exception while running ibtool...

### ISSUE THREAD

**Issue by Radagan** [ooper-shlab/SourceView-Swift#1]
First off, thank you for providing this conversion of SourceView to Swift. Unfortunately, there seems to be an error when building under 10.13 and Xcode 9. I noticed that Apple has also updated the Objective-C version to address this issue on 7/10. 

The error:
```
SourceView-Swift/SourceView/Base.lproj/Main.storyboard: Exception while running ibtool: Placeholder for identifier 'UpstreamPlaceholder-a1I-tS-eOl' was set to '<IBNSNibExternalObjectPlaceholder: 0x7ff19a09f4c0 identifier=UpstreamPlaceholder-v8j-0C-me4>', but the object was deallocated. Is it missing a strong reference in the storyboard/nib?
```

Any idea how to fix it in this version?

**Comment by ooper-shlab** [comment]
Thanks for reporting the issue. But, I cannot test building on 10.13, as I have not yet installed 10.13 beta.
And, as far as I can see, Apple's latest version of SourceView sample code is 8.0 2017-06-15, which the latest version of this repository is based on.

Building on 10.12.5 with Xcode 9 beta 3 succeeds without problems. If the issue happens only on 10.13,  I cannot check it until 10.13 being stable enough for production use. Maybe a few months after its public release.

**Comment by Radagan** [comment]
My mistake on the date, but that is the revision I'm referring to:

Version 8.0, 2017-06-15
Fixed build-time exception issue running ibtool on the storyboard file.

It cryptically alludes to something very similar to what I'm seeing under XCode 9 and 10.13. I understand if you haven't tried the beta yet--no worries. I'm not sure how to track down an issue with ibtool. Any advice would be welcome. It's still a good example even if it won't build. ;^)

**Comment by ooper-shlab** [comment]
Thanks for confirming the revision referred. Hope Apple will fix this issue before I can touch and test on 10.13.

**Comment by thierryH91200** [comment]
![capture d ecran 2018-05-14 18 30 54](https://user-images.githubusercontent.com/6251463/40010446-0a32738c-57a5-11e8-9d51-1b11cee2adb3.jpg)
 a new revision
